name: Deploy-Nodejs-Api-Eleicoes

env:
  RELEASE_PATH: /var/www/apieleicoes.projectdev.services/html

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x]
    
    steps:
    - uses: actions/checkout@v4

    - name: COPY_REPOSITORY_DATA_VIA_SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT}}
        source: '.'
        target: ${{ env.RELEASE_PATH }}

    - name: EXECUTING_REMOTE_COMMAND
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        run: |
          cd ${{ env.RELEASE_PATH }}
          pm2 restart app 

          